DROP TABLE if exists tb_category;
DROP TABLE if exists tb_order;
DROP TABLE if exists tb_order_item;
DROP TABLE if exists tb_payment;
DROP TABLE if exists tb_product;
DROP TABLE if exists tb_product_category;
DROP TABLE if exists tb_role;
DROP TABLE if exists tb_user;
DROP TABLE if exists tb_user_role;